import { Post } from "./src/types/map";

export const initialPosts: Post[] = [
  {
    id: "d1",
    type: "post",
    coordinate: { latitude: 37.471, longitude: 126.935 },
    emoji: "🍢",
    title: "붕어빵 판매 중",
    content: "붕어빵 3개 2,000원입니다.",
    createdAt: Date.now() - 100000,
    comments: [],
  },
  {
    id: "d2",
    type: "post",
    coordinate: { latitude: 37.469, longitude: 126.933 },
    emoji: "🚌",
    title: "버스 정류장 혼잡",
    content: "퇴근 시간이라 사람이 많습니다.",
    createdAt: Date.now() - 300000,
    comments: [],
  },
  {
    id: "d3",
    type: "post",
    coordinate: { latitude: 37.472, longitude: 126.936 },
    emoji: "🌧️",
    title: "갑자기 비 시작",
    content: "우산 챙기세요.",
    photo: "https://images.unsplash.com/photo-1515694346937-94d85e41e6f0?w=400",
    createdAt: Date.now() - 500000,
    comments: [],
  },
  {
    id: "d4",
    type: "post",
    coordinate: { latitude: 37.468, longitude: 126.934 },
    emoji: "🐱",
    title: "고양이 발견",
    content: "회색 고양이가 돌아다니고 있어요.",
    photo: "https://images.unsplash.com/photo-1514888286974-6c03e2ca1dba?w=400",
    createdAt: Date.now() - 700000,
    comments: [],
  },
  {
    id: "b1",
    type: "board",
    coordinate: { latitude: 37.475, longitude: 126.936 },
    emoji: "🛒",
    title: "동네 마트 소식",
    description: "세일/입고 정보를 공유하는 게시판입니다.",
    createdAt: Date.now() - 86400000,
    boardPosts: [
      {
        id: "bp1",
        emoji: "🥬",
        title: "오늘 채소 특가",
        content: "상추 1봉 1,000원",
        createdAt: Date.now() - 100000,
        comments: [],
      },
      {
        id: "bp2",
        emoji: "🍜",
        title: "라면 5+1 행사",
        content: "행사 코너 확인해보세요.",
        createdAt: Date.now() - 90000,
        comments: [],
      },
    ],
  },
  {
    id: "b2",
    type: "board",
    coordinate: { latitude: 37.465, longitude: 126.93 },
    emoji: "☕",
    title: "카페 코딩",
    description: "조용한 카페 좌석/혼잡도 공유",
    createdAt: Date.now() - 172800000,
    boardPosts: [
      {
        id: "bp3",
        emoji: "💺",
        title: "창가석 비었어요",
        content: "콘센트 자리 2석 가능",
        createdAt: Date.now() - 50000,
        comments: [],
      },
    ],
  },
  {
    id: "b3",
    type: "board",
    coordinate: { latitude: 37.478, longitude: 126.94 },
    emoji: "🏋️",
    title: "헬스장 정보",
    description: "운동 기구/혼잡도 공유 게시판",
    createdAt: Date.now() - 259200000,
    boardPosts: [
      {
        id: "bp4",
        emoji: "🏃",
        title: "런닝머신 대기 짧음",
        content: "현재 2대 비어있습니다.",
        createdAt: Date.now() - 200000,
        comments: [],
      },
    ],
  },
];
